### ISSUE TITLE
Request err 401

### ISSUE THREAD

**Issue by Fatpandac** [dedoussis/icloud-hide-my-email-chrome-extension#3]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/30423976/190897080-5965e601-b563-447a-8854-11785a2cd1bc.png">

**Comment by dedoussis** [comment]
Hey @Fatpandac!

Could you provide me with a bit more context on how this occurred? Did you try signing out and signing back in? 401 means that your session token is not valid anymore.

**Comment by dedoussis** [comment]
Note that the Hide My Email feature is only available for iCloud+ members. The base iCloud subscription does not include it.

**Comment by Fatpandac** [comment]
I subscripted iCloud+.
I tried to log in again when I got requests error whit 401, but it has not changed.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/30423976/191036913-aca3cbad-0065-41ee-8889-72804d2ac049.png">

**Comment by dedoussis** [comment]
@Fatpandac would you be able to paste me the response payload that is returned by the iCloud API?

In order to do this, you would need to open the dev console of the extension pop-up: While you have the extension popup window open, right click and select "Insect".

Once you have opened the dev console, you can try regenerating a new Hide My Email.

Then, you can navigate to the Network tab of the dev console and see the response returned by the iCloud API.

**Comment by Fatpandac** [comment]
Return 401 when request `https://p103-maildomainws.icloud.com/v1/hme/generate`
<img width="762" alt="image" src="https://user-images.githubusercontent.com/30423976/191046507-8d830868-75b1-4848-8160-8f80e3dbf057.png">

**Comment by Fatpandac** [comment]
OK, thank you so much.

**Comment by dedoussis** [comment]
@Fatpandac The fix has finally been published to the chrome web store (version 0.0.3). For some reason it took 2 weeks for the web store review team to approve it 🤷 

Let me know if it works for you and I will be closing this issue.

**Comment by Fatpandac** [comment]
Ok, I will check it late. Thanks again.

**Comment by Fatpandac** [comment]
It's working!

**Comment by dedoussis** [comment]
@Fatpandac Perfect! Closing.

**Comment by Fatpandac** [comment]
Em...cloud you build a version for Firefox?
